import { Pet } from "@/components/pet-card"

export const pets: Pet[] = [
  {
    id: "1",
    name: "Buddy",
    type: "dog",
    breed: "Golden Retriever",
    age: "2 years",
    gender: "male",
    location: "San Francisco, CA",
    image: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&h=600&fit=crop",
    description: "Buddy is a friendly and energetic Golden Retriever who loves to play fetch and go on long walks. He's great with kids and other dogs, making him the perfect family companion. Buddy is house-trained and knows basic commands.",
    temperament: ["Friendly", "Playful", "Loyal", "Energetic"],
    size: "large",
  },
  {
    id: "2",
    name: "Luna",
    type: "cat",
    breed: "British Shorthair",
    age: "1 year",
    gender: "female",
    location: "Los Angeles, CA",
    image: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=600&fit=crop",
    description: "Luna is a calm and affectionate British Shorthair who enjoys lounging in sunny spots and being petted. She's independent but loves to cuddle at night. Luna is perfect for apartment living and gets along well with calm dogs.",
    temperament: ["Calm", "Affectionate", "Independent", "Gentle"],
    size: "medium",
  },
  {
    id: "3",
    name: "Max",
    type: "dog",
    breed: "German Shepherd",
    age: "3 years",
    gender: "male",
    location: "Seattle, WA",
    image: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600&h=600&fit=crop",
    description: "Max is an intelligent and loyal German Shepherd with a heart of gold. He's been trained in basic obedience and loves learning new tricks. Max needs an active family who can provide him with daily exercise and mental stimulation.",
    temperament: ["Intelligent", "Loyal", "Protective", "Active"],
    size: "large",
  },
  {
    id: "4",
    name: "Milo",
    type: "cat",
    breed: "Maine Coon",
    age: "4 years",
    gender: "male",
    location: "Portland, OR",
    image: "https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=600&h=600&fit=crop",
    description: "Milo is a majestic Maine Coon with a gentle personality. Despite his large size, he's incredibly gentle and loves to follow his humans around the house. Milo is great with children and other pets.",
    temperament: ["Gentle", "Sociable", "Curious", "Affectionate"],
    size: "large",
  },
  {
    id: "5",
    name: "Bella",
    type: "dog",
    breed: "French Bulldog",
    age: "1 year",
    gender: "female",
    location: "Austin, TX",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&h=600&fit=crop",
    description: "Bella is an adorable French Bulldog with a playful and loving personality. She's great in apartments due to her moderate energy levels and loves to be the center of attention. Bella is fully vaccinated and spayed.",
    temperament: ["Playful", "Loving", "Adaptable", "Social"],
    size: "small",
  },
  {
    id: "6",
    name: "Oliver",
    type: "cat",
    breed: "Ragdoll",
    age: "2 years",
    gender: "male",
    location: "Denver, CO",
    image: "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=600&h=600&fit=crop",
    description: "Oliver is a stunning Ragdoll who lives up to his breed's reputation of being a gentle giant. He loves to be held and will go limp in your arms. Oliver is perfect for families looking for a calm, affectionate companion.",
    temperament: ["Relaxed", "Gentle", "Loving", "Docile"],
    size: "large",
  },
  {
    id: "7",
    name: "Charlie",
    type: "dog",
    breed: "Labrador Retriever",
    age: "4 years",
    gender: "male",
    location: "Chicago, IL",
    image: "https://images.unsplash.com/photo-1579213838058-5cc4a5a6b8f5?w=600&h=600&fit=crop",
    description: "Charlie is a classic Labrador who loves water, fetch, and most importantly, his humans. He's well-trained, great with kids of all ages, and has a calm demeanor despite his playful nature. Charlie would thrive in a home with a yard.",
    temperament: ["Friendly", "Outgoing", "Gentle", "Intelligent"],
    size: "large",
  },
  {
    id: "8",
    name: "Cleo",
    type: "cat",
    breed: "Siamese",
    age: "3 years",
    gender: "female",
    location: "Miami, FL",
    image: "https://images.unsplash.com/photo-1513245543132-31f507417b26?w=600&h=600&fit=crop",
    description: "Cleo is a vocal and loving Siamese who will keep you entertained with her conversations. She's highly intelligent and can be taught tricks. Cleo bonds deeply with her humans and prefers to be the only pet in the household.",
    temperament: ["Vocal", "Intelligent", "Loving", "Playful"],
    size: "medium",
  },
  {
    id: "9",
    name: "Rocky",
    type: "dog",
    breed: "Boxer",
    age: "2 years",
    gender: "male",
    location: "Phoenix, AZ",
    image: "https://images.unsplash.com/photo-1558929996-da64ba858215?w=600&h=600&fit=crop",
    description: "Rocky is a fun-loving Boxer with endless energy and a heart full of love. He's great with active families and loves to play with children. Rocky needs regular exercise but rewards his family with unwavering loyalty and affection.",
    temperament: ["Energetic", "Fun-loving", "Loyal", "Brave"],
    size: "large",
  },
  {
    id: "10",
    name: "Willow",
    type: "cat",
    breed: "Persian",
    age: "5 years",
    gender: "female",
    location: "San Diego, CA",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&h=600&fit=crop",
    description: "Willow is a beautiful Persian with a sweet and gentle temperament. She enjoys quiet environments and would be perfect for someone looking for a calm, low-energy companion. Willow requires regular grooming but rewards you with endless purrs.",
    temperament: ["Sweet", "Quiet", "Gentle", "Relaxed"],
    size: "medium",
  },
  {
    id: "11",
    name: "Cooper",
    type: "dog",
    breed: "Beagle",
    age: "1 year",
    gender: "male",
    location: "Nashville, TN",
    image: "https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600&h=600&fit=crop",
    description: "Cooper is an adventurous Beagle with an excellent nose and curious nature. He loves exploring and would do well with an active owner who enjoys outdoor activities. Cooper is good with other dogs and loves meeting new people.",
    temperament: ["Curious", "Merry", "Friendly", "Determined"],
    size: "medium",
  },
  {
    id: "12",
    name: "Daisy",
    type: "dog",
    breed: "Corgi",
    age: "3 years",
    gender: "female",
    location: "Boston, MA",
    image: "https://images.unsplash.com/photo-1612536057832-2ff7ead58194?w=600&h=600&fit=crop",
    description: "Daisy is an adorable Corgi with a big personality in a small package. She's intelligent, eager to please, and loves to herd (including small children!). Daisy is house-trained and knows several commands.",
    temperament: ["Bold", "Friendly", "Intelligent", "Active"],
    size: "small",
  },
]

export const breeds = {
  dog: ["Golden Retriever", "German Shepherd", "French Bulldog", "Labrador Retriever", "Boxer", "Beagle", "Corgi"],
  cat: ["British Shorthair", "Maine Coon", "Ragdoll", "Siamese", "Persian"],
  rabbit: ["Holland Lop", "Mini Rex", "Netherland Dwarf"],
  bird: ["Parakeet", "Cockatiel", "Canary"],
  other: ["Hamster", "Guinea Pig", "Ferret"],
}

export const locations = [
  "San Francisco, CA",
  "Los Angeles, CA",
  "Seattle, WA",
  "Portland, OR",
  "Austin, TX",
  "Denver, CO",
  "Chicago, IL",
  "Miami, FL",
  "Phoenix, AZ",
  "San Diego, CA",
  "Nashville, TN",
  "Boston, MA",
]
