-- Insert pet categories
INSERT INTO pet_categories (name, description) VALUES
('Dog', 'Loyal and loving canine companions'),
('Cat', 'Independent and graceful feline friends'),
('Rabbit', 'Gentle and curious small pets'),
('Bird', 'Colorful and melodious feathered companions'),
('Guinea Pig', 'Social and affectionate rodent friends')
ON CONFLICT (name) DO NOTHING;

-- Insert sample pets
INSERT INTO pets (name, breed, type, age_months, gender, size, image_url, description, location, vaccinated, adoption_status, category_id, health_status, vaccination_status, color) VALUES
(
  'Max',
  'German Shepherd',
  'Dog',
  36,
  'Male',
  'Large',
  'https://images.unsplash.com/photo-1568572933382-74d440642117?w=500&h=500&fit=crop',
  'Max is a friendly and energetic German Shepherd who loves outdoor adventures and playing fetch. He''s well-trained and great with families.',
  'New York',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Dog'),
  'Healthy',
  'Fully Vaccinated',
  'Black and Tan'
),
(
  'Luna',
  'Golden Retriever',
  'Dog',
  24,
  'Female',
  'Large',
  'https://images.unsplash.com/photo-1633722715463-d30628519d30?w=500&h=500&fit=crop',
  'Luna is a beautiful and gentle Golden Retriever with a heart of gold. She loves cuddles and is perfect for active families.',
  'Los Angeles',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Dog'),
  'Healthy',
  'Fully Vaccinated',
  'Golden'
),
(
  'Bella',
  'British Shorthair',
  'Cat',
  18,
  'Female',
  'Medium',
  'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500&h=500&fit=crop',
  'Bella is a calm and affectionate British Shorthair who enjoys quiet moments and gentle petting. She''s perfect for apartment living.',
  'Chicago',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Cat'),
  'Healthy',
  'Fully Vaccinated',
  'Gray'
),
(
  'Charlie',
  'Labrador Retriever',
  'Dog',
  42,
  'Male',
  'Large',
  'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&h=500&fit=crop',
  'Charlie is an older gentleman dog with a calm demeanor. He''s perfect for someone looking for a loyal and quiet companion.',
  'Houston',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Dog'),
  'Healthy',
  'Fully Vaccinated',
  'Black'
),
(
  'Whiskers',
  'Tabby Mix',
  'Cat',
  12,
  'Male',
  'Small',
  'https://images.unsplash.com/photo-1519052537793-e21dde8e387f?w=500&h=500&fit=crop',
  'Whiskers is a playful and curious kitten full of energy and personality. He loves interactive toys and climbing.',
  'Phoenix',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Cat'),
  'Healthy',
  'Fully Vaccinated',
  'Orange Tabby'
),
(
  'Daisy',
  'Beagle',
  'Dog',
  30,
  'Female',
  'Small',
  'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=500&h=500&fit=crop',
  'Daisy is a sweet and energetic Beagle who loves to follow scents and play. She''s great with kids and other pets.',
  'Philadelphia',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Dog'),
  'Healthy',
  'Fully Vaccinated',
  'Brown and White'
),
(
  'Oliver',
  'Persian',
  'Cat',
  24,
  'Male',
  'Medium',
  'https://images.unsplash.com/photo-1567843820643-24c3142e9b8e?w=500&h=500&fit=crop',
  'Oliver is a majestic Persian cat with a luxurious coat. He enjoys lounging in sunny spots and being pampered.',
  'San Antonio',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Cat'),
  'Healthy',
  'Fully Vaccinated',
  'White'
),
(
  'Rocky',
  'Bulldog',
  'Dog',
  48,
  'Male',
  'Medium',
  'https://images.unsplash.com/photo-1583511655857-d19db992cb74?w=500&h=500&fit=crop',
  'Rocky is a sturdy and lovable Bulldog with a gentle temperament. He''s perfect for laid-back families who want a calm companion.',
  'San Diego',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Dog'),
  'Healthy',
  'Fully Vaccinated',
  'Fawn'
),
(
  'Mittens',
  'Siamese',
  'Cat',
  15,
  'Female',
  'Small',
  'https://images.unsplash.com/photo-1513360371669-4a5f8c9d5c39?w=500&h=500&fit=crop',
  'Mittens is a vocal and affectionate Siamese cat who loves attention. She''s very interactive and playful with her favorite humans.',
  'Dallas',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Cat'),
  'Healthy',
  'Fully Vaccinated',
  'Cream and Brown'
),
(
  'Buddy',
  'Poodle Mix',
  'Dog',
  20,
  'Male',
  'Small',
  'https://images.unsplash.com/photo-1601758228632-62e70f3c7a4d?w=500&h=500&fit=crop',
  'Buddy is a hypoallergenic Poodle Mix who''s perfect for allergy-prone families. He''s intelligent, friendly, and very trainable.',
  'San Jose',
  true,
  'Available',
  (SELECT id FROM pet_categories WHERE name = 'Dog'),
  'Healthy',
  'Fully Vaccinated',
  'White'
);
